theme: jekyll-theme-slate
title: Electric Vehicle Electricity Consumption Model
description: An illustrative demonstration of the effects of different algorithms and infrastructure properties on the charging of electric vehicles.
